[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
included-patches = "'Hide ads' 'Anonymous story viewing' 'Remove build expired popup' 'Sanitize sharing links'"
exclusive-patches = true

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[GooglePhotos]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"

[Soundcloud]
apkmirror-dlurl = "https://apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
